name: Prepare for FHEM update

on: [push]

jobs:
  update:
    env:
      CONTROLS_FILENAME: controls_Buienradar.txt
      DOCUMENTATION_SCRIPT: build/documentation.sh
    runs-on: ubuntu-latest
    steps:
      - name: Update Environment
        run: |
          sudo apt-get install -y pandoc tidy cpanminus
          cpanm --sudo Data::Dump::Color Readonly
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Add Documentation
        run: |
          bash $DOCUMENTATION_SCRIPT
      - name: Update CHANGED file
        run: |
          LOG=$(date +"%Y-%m-%d")
          LOG+=" - $(git log -1 --pretty=%B)"
          echo "$LOG" | cat - CHANGED > temp && mv temp CHANGED
      - name: Update controls file
        run: |
          perl build/create_controlfile -s lib -s FHEM -e .pm -p -v -c $CONTROLS_FILENAME
      - name: git commit back
        run: |
          git config --global user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGED $CONTROLS_FILENAME || true
          git log --no-merges -1 --name-only --pretty=format: | grep -Eo '[0-9]{2}_.*.pm$' && git commit CHANGED $CONTROLS_FILENAME -m "Automatic updated controls and CHANGED" || true
      - name: Push changed files back to repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}