name: Prepare for FHEM update

on: [push]

jobs:
  update:
    env:
      CONTROLS_FILENAME: controls_Buienradar.txt
      CONTROLS_CREATE_SCRIPT: build/prepare_controls.sh
    runs-on: ubuntu-latest
    steps:
      - name: Update Environment
        run: sudo apt-get install -y pandoc tidy
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: update controls files
        uses: fhem/fhem-controls-actions@master
        with:
          filename: $CONTROLS_FILENAME
      - name: Update Controls
        run: |
          bash $CONTROLS_CREATE_SCRIPT $CONTROLS_FILENAME
          cat $CONTROLS_FILENAME
      - name: update CHANGED
        run: |
          LOG=$(date +"%Y-%m-%d")
          LOG+=" - $(git log -1 --pretty=%B)"
          echo "$LOG" | cat - CHANGED > temp && mv temp CHANGED
      - name: git commit back
        run: |
          git config --global user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGED $CONTROLS_FILENAME || true
          git log -1 --name-only --pretty=format: | grep -Eo '[0-9]{2}_.*.pm$' && git commit CHANGED $CONTROLS_FILENAME -m "Automatic updated controls and CHANGED" || true
      - name: git push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}